### ISSUE TITLE
Thermal Dynamics pipes crash game when try to pump MatterPlasma from Decomposer

### ISSUE THREAD

**Issue by DevTimur** [MatterOverdrive/MatterOverdrive-Legacy-Edition#105]
https://pastebin.com/2980PaXA

ThermalDynamics-1.12.2-2.3.10.4-universal
MatterOverdrive-1.12.2-0.6.0.75-universal
CLib-1.0.2.31-universal.jar

**Comment by adrwa** [comment]
TD really shouldn't be trying to drain an empty block -_-

**Comment by DevTimur** [comment]
[TD trying to suck an empty block](http://i.imgur.com/EghcKa8.gif)
Lol!
