### ISSUE TITLE
Crash with galacticraft

### ISSUE THREAD

**Issue by manuwwa** [MatterOverdrive/MatterOverdrive-Legacy-Edition#106]
Game is crashing shortly after my rocket from galacticraft enters space (map from galacticraft should show in this situation), but I've been told this crash is related to matteroverdrive, not galacticraft

Here are all the logs:
[fml-client-latest.log](https://github.com/MatterOverdrive/MatterOverdrive/files/1830763/fml-client-latest.log)
[latest.log](https://github.com/MatterOverdrive/MatterOverdrive/files/1830764/latest.log)

Here's link to discusion on galacticraft github:
https://github.com/micdoodle8/Galacticraft/issues/3257

**Comment by adrwa** [comment]
Were you in a galacticraft rocket by any chance?

**Comment by manuwwa** [comment]
Yes, correct.

**Comment by adrwa** [comment]
Yeah, this is GC's fault, either their rocket display name is null or their UUID.
