### ISSUE TITLE
[1.12.2] crash with Applied Energistics 2

### ISSUE THREAD

**Issue by Enomis-lb** [MatterOverdrive/MatterOverdrive-Legacy-Edition#108]
MO crashes with AE2

AE2 appliedenergistics2-rv5-stable-11
MO MatterOverdrive-1.12.2-0.6.0.108
Forge 1.12.2-forge1.12.2-14.23.2.2628

it seems to me that AE2 tries to create facades with blocks like matteroverdrive:alien_stone, etc...

(I'm sorry for any grammatical errors but English is not my native language)

**Comment by adrwa** [comment]
I need a crash report to see what the error is

**Comment by Enomis-lb** [comment]
[crash-2018-03-27_23.14.47-client.txt](https://github.com/MatterOverdrive/MatterOverdrive/files/1853835/crash-2018-03-27_23.14.47-client.txt)

**Comment by adrwa** [comment]
Not a bug, change the AE2 dimension id in their config
