### ISSUE TITLE
Crash when starting game 

### ISSUE THREAD

**Issue by KiraLinux** [MatterOverdrive/MatterOverdrive-Legacy-Edition#109]
The game crashes at startup
I threw all the files in the archive

1.12.2-forge1.12.2-14.23.2.2639
MatterOverdrive-1.12.2-0.6.0.144-universal
CLib-1.0.2.47-universal

[crash_and_logs.zip](https://github.com/MatterOverdrive/MatterOverdrive/files/1854084/crash_and_logs.zip)

**Comment by adrwa** [comment]
you're using a version of CLib which isnt released, thats not recommended

**Comment by KiraLinux** [comment]
Can I use this MatterOverdrive-1.12.2-0.6.0.144-universal and CLib-1.0.2.31-universal together?
