### ISSUE TITLE
Android Player Skin

### ISSUE THREAD

**Issue by ghost** [MatterOverdrive/MatterOverdrive-Legacy-Edition#110]
Is there a way to disable the android player skin? AKA let them continue using their current skin whilst being an Android?

Anywhere in code etc that would be easy to comment out?

Mainly, Mo' Bends works, its just it displays the Android skin and the player's skin on top of each other. Kinda creepy.

**Comment by adrwa** [comment]
As far as i know the android player skin isnt enabled in 1.12

**Comment by ghost** [comment]
I don't use 1.12. Know where the code lies in the 1.7.10 branch?

**Comment by adrwa** [comment]
1.7.10 is no longer supported
