### ISSUE TITLE
Crash when using pattern terminal

### ISSUE THREAD

**Issue by ghost** [MatterOverdrive/MatterOverdrive-Legacy-Edition#111]
I was playing the game today, and when i tried to access pattern terminal search feature, it crashed the game
[crash-2018-03-31_16.10.46-server.txt](https://github.com/MatterOverdrive/MatterOverdrive/files/1865494/crash-2018-03-31_16.10.46-server.txt)

**Comment by adrwa** [comment]
already fixed
