### ISSUE TITLE
Dimension ID config option

### ISSUE THREAD

**Issue by GeorgeDeac** [MatterOverdrive/MatterOverdrive-Legacy-Edition#116]
It would be nice to have the option to change the dimension id.

**Comment by adrwa** [comment]
MO has no dimensions

**Comment by GeorgeDeac** [comment]
Wasn't there a WIP dimension called "alien world" introduced recently? Cause every time install matter overdrive I get an ID conflict with applied energistics on dimension 2.

**Comment by adrwa** [comment]
No that dimension got removed

**Comment by GeorgeDeac** [comment]
Oh I see, sorry my mistake.. Guess I should update to the latest beta :)
