### ISSUE TITLE
[1.12.2] Crush with MOItemEnergyContainer

### ISSUE THREAD

**Issue by Rumaruka** [MatterOverdrive/MatterOverdrive-Legacy-Edition#117]
Crushlog - https://pastebin.com/7Hz2qjmW

**Comment by lag42** [comment]
i got the same crash just now

**Comment by adrwa** [comment]
Please try with forge version 14.23.2.2654

**Comment by Rumaruka** [comment]
forge version 14.23.2.2654 - running =)

**Comment by adrwa** [comment]
yeah, thought so

**Comment by adrwa** [comment]
can you try latest forge with this jar http://jenkins.k-4u.nl/job/MatterOverdrive/lastSuccessfulBuild/artifact/build/libs/MatterOverdrive-1.12.2-0.6.0.146-universal.jar

**Comment by Rumaruka** [comment]
I think Forge Team change Energy API =(

**Comment by adrwa** [comment]
did it crash?

**Comment by Rumaruka** [comment]
Wait 5 - 10 min =)

**Comment by Rumaruka** [comment]
Nope
Log - https://pastebin.com/8wb7wERw
