### ISSUE TITLE
[1.12.2] Androids Show Death Message [Mod Interaction]

### ISSUE THREAD

**Issue by MokahTGS** [MatterOverdrive/MatterOverdrive-Legacy-Edition#118]
If you have the Death Messages mod and Matter Overdrive, you will see death messages for hostile androids that die in the world as if they were players.  For example, you will see them die to Forestry Bees or lava.  You can also see their name plates as if they were players.

I'm not sure if this intentional but it seems odd that the game seems to think they are players.

**Comment by adrwa** [comment]
since MO doesnt do this by itself, i cant fix it, and its not really a bug, its whatever mod is putting the messages job to filter which messages to post
