### ISSUE TITLE
Crash generating mad scientist in village

### ISSUE THREAD

**Issue by evhub** [MatterOverdrive/MatterOverdrive-Legacy-Edition#120]
See crash report [here](https://gist.github.com/evhub/7f00cf10615687c134b057f2c41918b8). Traceback seems to suggest a matter overdrive issue, but I also see recurrent complex, biomes o plenty, and forestry showing up there, so it's possible this is an issue with one of those mods instead. In that case, feel free to close this issue.

**Comment by adrwa** [comment]
Duplicate of #112
