### ISSUE TITLE
android form dying

### ISSUE THREAD

**Issue by Anarchy079** [MatterOverdrive/MatterOverdrive-Legacy-Edition#121]
#### Issue Description:
when confronting a skeleton

#### What happens:
regardless of what armor your wearing an skeleton archer will insta kill you

#### What you expected to happen:
not to die instantly?

#### How to reproduce:
just become an android and get shot by a skeleton archer

#### Affected Versions (Do *not* use "*latest*"):

- CLib: 1.0.2.31 Universal.jar
- MatterOverdrive: 1.12.2 0.6.0.144 beta 4
- Forge: 14.23.3.2655
- Minecraft: 1.12.2

#### Crash report, if relevent
[pastebin/gist link here]

**Comment by Muirrum** [comment]
Alright I'll take a look.

**Comment by Muirrum** [comment]
I just loaded up latest version and it took a good five hits for me to be killed.
