### ISSUE TITLE
Config Option/Feature Request

### ISSUE THREAD

**Issue by Tellik** [MatterOverdrive/MatterOverdrive-Legacy-Edition#122]
Black holes do not suck up bedrock blocks that are placed in the world. https://gyazo.com/a3c804682d72872cabdd45f1a9238f02

While I know that this is probably as intended, I would like to request the ability of them to absorb ALL blocks, and with two config file options. One to be able to black list blocks specifically that shouldn't be absorbed. (This could include the defaults that it normally has hard coded to black list), And to change the resistance of either blocks in general or specifically identified.

**Comment by adrwa** [comment]
eh, this is a bit out of scope, it uses the hardness of the blocks and thats all it'll use, bedrock should never be able to be eaten by a blackhole and i'll never allow it to be so
