### ISSUE TITLE
[1.12.2] Conflicts with Sildurs Shaders

### ISSUE THREAD

**Issue by TimeConqueror** [MatterOverdrive/MatterOverdrive-Legacy-Edition#123]
#### Issue Description:
I play with modpack which includes MatterOverdrive and Optifine (for shaders). I turned on Sildurs Vibrant Shaders and saw 3 bugs:
1. **DataPad vanishing**. 
When you try to take DataPad in hand, its texture vanishes.
![image](https://user-images.githubusercontent.com/25156941/39521964-5becec42-4e19-11e8-8d75-4e8279ebcc17.png)

2. **Glitch with weapons**
When you try to take any weapon in hand, the world becomes transparent.

_Without weapon:_
![image](https://user-images.githubusercontent.com/25156941/39522163-2e364a22-4e1a-11e8-9d73-25624cb6c09f.png)

_With weapon_:
![image](https://user-images.githubusercontent.com/25156941/39522044-b04b8d66-4e19-11e8-9f67-1c62528725ea.png)

3. **Glitch with Entity HUD**
When you use Scanner on blocks or look at some creature, being an android, the HUD glitches.
![image](https://user-images.githubusercontent.com/25156941/39522141-17b59c26-4e1a-11e8-813f-c3cb36b9331a.png)

As for the third problem, maybe is there some variant to turn off this HUD, when you are android?

#### Affected Versions:
- CLib: 1.0.2.31
- MatterOverdrive: 1.12.2 0.6.0.144 BETA 4.1 (Name of file: MatterOverdrive-1.12.2 -0.6.0.148
- Forge: 1.12.2 - 14.23.3.2655
- Minecraft: 1.12.2

**Comment by adrwa** [comment]
Sorry but since optifine hacks so many of minecraft's internals it is impossible for me to support shaders if they do not work
