### ISSUE TITLE
Matter Registry not working for Modded Items

### ISSUE THREAD

**Issue by SupremeDraco** [MatterOverdrive/MatterOverdrive-Legacy-Edition#124]
#### Issue Description:
I used the Matter Register command (specifically Itemstack, due to the fact Ore would not work for what I was doing), it worked for a while, and the items are placed into the config and can be cloned and analyzed, but as soon as I leave the world, weither it be crash, computer shutdown, or simply clicking exit of MC, and come back, the items I had just registered no longer are registered , however they're still in the config. I've tried modifying the config, changing the numbers or anything really, but it does not work, the effect remains the same.
The only way to fix it is to re-register, but that just repeats it all over again as soon as I leave.

#### What happens:
Anything I register will unregister as soon as I log out of MC, but will remain in the config

#### What you expected to happen:
I expect that when I register an item, that it remains registered, even when I log out, so that I may use the mod on them

#### How to reproduce:
Use the /matter_register command to register an item, and log out of MC, and log back on, also check config

#### Affected Versions (Do *not* use "*latest*"):

- CLib: 1.0.2.31
- MatterOverdrive: 1.12.2-0.6.0.148
- Forge: 14.23.2.2611
- Minecraft: 1.12.2

#### Crash report, if relevent
There is no crash to report

EDIT: I said it was modded items, but I editted it because it's also happening with normal items to, as I just found out sadly.

**Comment by adrwa** [comment]
Can you try with this jar? recently i did a lot of changes to the matter registry to improve its detection, http://jenkins.k-4u.nl/job/MatterOverdrive/153/artifact/build/libs/MatterOverdrive-1.12.2-0.6.0.153-universal.jar

**Comment by SupremeDraco** [comment]
Unfortunately it didn't work, the same thing is still happening, exactly how it was before. I also tested with my other mods, and repeated this when it just MatterOverdrive and CLib, the mods aren't conflicting.

**Comment by adrwa** [comment]
are they registered after closing and reopening the game?

**Comment by SupremeDraco** [comment]
Sadly not, after closing and reopening the game, any new item registered isn't not registered anymore.
