### ISSUE TITLE
Rogue Androids have a strange head overlay

### ISSUE THREAD

**Issue by Shahelion** [MatterOverdrive/MatterOverdrive-Legacy-Edition#129]
#### Issue Description:
Rogue Android heads appear to be all white. Further inspection reveals this to be on top of the normal head, which is still there just not visible. I have iChun's Shatter mod which makes the head and overlay fly in different directions upon death, otherwise I would never have seen that the normal one is underneath.
![2018-05-11_15 51 42](https://user-images.githubusercontent.com/6917535/39950071-bb18bb62-5533-11e8-9b4d-a33bae28c157.png)
![2018-05-11_15 51 45](https://user-images.githubusercontent.com/6917535/39950072-bb382240-5533-11e8-9db0-18871e265011.png)

#### Affected Versions (Do *not* use "*latest*"):

- CLib: 1.0.2.31
- MatterOverdrive: 0/6/0/157
- Forge: 2655
- Minecraft: 1.12.2

**Comment by Alaberti** [comment]
![2018-05-12_22 45 40](https://user-images.githubusercontent.com/10929796/39963618-9766c9b2-5636-11e8-8111-f479a85d2997.png)

+1, also verified not an issue with optifine (confirmed issue with and without)

**Comment by Shahelion** [comment]
I don't even have Optifine, so definitely not that.

Also, it looks like it doesn't affect all of the androids, just some of them. I assume it's one particular head that's having issues.

**Comment by slava110** [comment]
File matteroverdrive\textures\entities\android.png with white background on CurseForge.

**Comment by Muirrum** [comment]
I'll take a look

**Comment by Buuz135** [comment]
https://github.com/MatterOverdrive/MatterOverdrive/pull/144
