### ISSUE TITLE
1.12.2 Androids stuffocate on the moon

### ISSUE THREAD

**Issue by MagnusHellstrom** [MatterOverdrive/MatterOverdrive-Legacy-Edition#130]
#### Issue Description:
Not really sure if this is a bug or not but from reading past issues, I can see it was implemented at one point, android suffocate on other planets in Galacticraft.

#### What happens:
Androids Suffocate.

#### What you expected to happen:
Androids not suffocating.

#### How to reproduce:
Go to moon,
Suffocate.

#### Affected Versions (Do *not* use "*latest*"):

- CLib: 1.0.2.31
- MatterOverdrive: MatterOverdrive-1.12.2-0.6.0.148-universal
- Forge: 14.23.3.2678
- Minecraft: 1.12.2

#### Crash report, if relevent
Not relevant.

**Comment by Alaberti** [comment]
@radfast Is this something you would have to build compatibility for?

**Comment by adrwa** [comment]
MO wont be adding support for galacticraft or advanced rocketry oxygen or any other system

**Comment by radfast** [comment]
@MagnusHellstrom  in Galacticraft we already made it so that MO androids are detected as entities which do not need oxygen in space, since about 2 years ago...    If that's not working then we can take a look, please open a new issue at [Galacticraft issues list](https://github.com/micdoodle8/Galacticraft/issues) - please specify _exact_ Galacticraft and MO version numbers and steps to reproduce.

**Comment by adrwa** [comment]
@radfast MO in 1.12 changed its modid to "matteroverdrive" instead of "mo", if you havent updated to that it wont work

**Comment by radfast** [comment]
That'll be it then!  Thank you, fixed in our next release.

**Comment by radfast** [comment]
Sorry, I need help - how do I get the `AndroidPlayer` object associated with a player in the current 1.12.2 code?

Previously we did it like this:

    Object android = AndroidPlayer.get(entityPlayer);
    boolean isAndroid = android.isAndroid();

**Comment by adrwa** [comment]
instead of ```AndroidPlayer.get(entityPlayer)``` use ```MOPlayerCapabilityProvider.GetAndroidCapability(entityPlayer)```

**Comment by radfast** [comment]
awesome, thank you
