### ISSUE TITLE
Clint Crash MatterOverdrive and TheOneprobe

### ISSUE THREAD

**Issue by IchigoGames** [MatterOverdrive/MatterOverdrive-Legacy-Edition#131]
#### Issue Description:
clint crash reporting for a user on my server so i do not know more then that tho from what i see in the crash report it looks like a issue with matteroverdrive and the one probe i reported to one probe and was told the issue was not with there mod but with matter overdrive and to report it here.

#### What happens:
clint crash

#### What you expected to happen:
not crash 
#### How to reproduce:
not sure
#### Affected Versions (Do *not* use "*latest*"):

- CLib:1.0.2.31-universal
- MatterOverdrive:-1.12.2-0.6.0.157-universal
- Forge:2655
- Minecraft:1.12.2
-theoneprobe-1.12-1.4.22

#### Crash report, if relevent
https://pastebin.com/e0x6Wv1c

**Comment by Muirrum** [comment]
What were you doing when the crash happened?

**Comment by IchigoGames** [comment]
it was not me who crashed but some one playing my pack and server i asked him before and no answer now he says he can't remember so nvm.

**Comment by adrwa** [comment]
thats not how crash reports work

**Comment by adrwa** [comment]
please dont report another issue if you're just gonna close it and not give the info needed

**Comment by IchigoGames** [comment]
if i had the info i would of gave it.

**Comment by Muirrum** [comment]
I think what Coded is getting at here is that you shouldn't have made the issue. The person who actually had the crash should have made the issue.
