### ISSUE TITLE
Crash when loading 

### ISSUE THREAD

**Issue by kave777** [MatterOverdrive/MatterOverdrive-Legacy-Edition#139]
#### What happens:
Minecraft crashes 

#### What you expected to happen:
I dont know

#### Affected Versions (Do *not* use "*latest*"):

- CLib: CLib-1.0.2.31-universal
- MatterOverdrive: MatterOverdrive-1.12.2-0.6.0.157-universal
- Forge: forge-1.12.2-14.23.3.2655-universal
- Minecraft: 1.12.2

#### Crash report, if relevent
https://paste.ee/p/dWWB3

**Comment by kave777** [comment]
There are a lot of ASM-related issues in the log, and I don't know what would cause those

**Comment by Muirrum** [comment]
Can we get the actual crash report instead of the startup log?

**Comment by kave777** [comment]
https://paste.ee/p/Z9q2L

**Comment by Muirrum** [comment]
So did it happen when the game was starting up or loading a world?

**Comment by kave777** [comment]
It happens while starting a game

**Comment by Muirrum** [comment]
I'm not getting any errors with that. Can you try it with just MO?
