### ISSUE TITLE
Pattern not showing up in the Pattern Terminal

### ISSUE THREAD

**Issue by IBriXXI** [MatterOverdrive/MatterOverdrive-Legacy-Edition#142]
#### Issue Description:
The Patterns I put into the Pattern Storage aren't showing up in the Pattern Monitor

#### What happens:
I analyze an Item (for ex. gravel) with the Analyzer and it appears to be on the Pattern drive. But it doesn't show up in the Pattern Monitor (scanned it to 100%)

#### What you expected to happen:
The Pattern appearing on the Pattern Monitor

#### How to reproduce:
Added screenshots

#### Affected Versions (Do *not* use "*latest*"):

- CLib: 1.0.2.31
- MatterOverdrive: 1.12.2-0.6.0.157
- Forge: 14.23.3.2675
- Minecraft: 1.12.2
![2018-06-01_22 07 21](https://user-images.githubusercontent.com/39710321/40861855-d67ea188-65ea-11e8-8790-4a862585c833.png)
![2018-06-01_22 07 38](https://user-images.githubusercontent.com/39710321/40861863-df766424-65ea-11e8-96fd-da69f63f6481.png)

#### Crash report, if relevent
[pastebin/gist link here]

**Comment by IBriXXI** [comment]
Anther Problem: I am scanning Items with the Data Pad. The Matter Scanner is pretty much useless.

**Comment by Taylor-Houthoofd** [comment]
I have the same problem. It kind of kills the fun of this mod for me; that particular feature is the main reason for playing the mod in the first place.

**Comment by TheStrategistNS** [comment]
I have the same problem. It kind of defeats the purpose of the mod for me; this part of it was the reason I got the mod in the first place

**Comment by SyntaxError73** [comment]
This bug also deters me from using the mod. I too have only gotten the mod for the matter network.

**Comment by webtyphoon** [comment]
+1

MC 1.12.2
forge 14.23.3.2655
CLib 1.0.2.31
MO 1.12.2-0.6.0.157

Also the refresh icon/button isn't showing up

![2018-06-15_08 45 04](https://user-images.githubusercontent.com/6331771/41454453-b7d9b7c4-7079-11e8-9acf-0652101678d0.png)
![2018-06-15_08 45 14](https://user-images.githubusercontent.com/6331771/41454454-b7f4cdfc-7079-11e8-97f8-3751c4b42cf0.png)

**Comment by adrwa** [comment]
I'm unable to reproduce, the patterns show up as far as i can see https://i.imgur.com/fIjkqzH.png https://i.imgur.com/Hf0uB4i.png

**Comment by IBriXXI** [comment]
It still does not work for me, can you show how you created the Matter Network? maybe it's a mistake from my side :/

**Comment by adrwa** [comment]
https://i.imgur.com/Zwt3Vqb.png

**Comment by IBriXXI** [comment]
It does not work for me, here some screenshots:
(I`m using a Modpack, maybe thats the problem?)
![modinfo](https://user-images.githubusercontent.com/39710321/41614994-61383dee-73fa-11e8-9471-705a796a956d.png)
![build](https://user-images.githubusercontent.com/39710321/41614995-62a14ce8-73fa-11e8-909d-953be277542b.png)
![pattern drive](https://user-images.githubusercontent.com/39710321/41614998-6533e36c-73fa-11e8-82ae-71411404b996.png)
![pattern monitor configuration](https://user-images.githubusercontent.com/39710321/41614999-65ee4216-73fa-11e8-8fc2-c8942b950322.png)
![pattern monitor](https://user-images.githubusercontent.com/39710321/41615001-66cc86a2-73fa-11e8-9327-f2c9ad4bde3d.png)

**Comment by webtyphoon** [comment]
The same over here on singleplayer and on a server. I build it on some tutorials on utube and also I tried ur built. I use this modpack - [Time](https://minecraft.curseforge.com/projects/minecraft-time) - maybe a mod inside will make problems. Is there a way how to check this?
