### ISSUE TITLE
Omnitool can't mine certain blocks

### ISSUE THREAD

**Issue by Shahelion** [MatterOverdrive/MatterOverdrive-Legacy-Edition#150]
#### Issue Description:
I figured it might be better to just make a fresh issue report for this. I can't see any consistency in which blocks it can or cannot break, except that every block with the issue so far has been a pickaxe-needed block. Here's an Imgur album showing some examples: https://imgur.com/a/KSdbkpR

#### What happens:
The omnitool takes a very long time to break the block, and it doesn't drop. Same as not using a tool at all.

#### What you expected to happen:
For it to break the block in question like the normal tool required.

#### How to reproduce:
Get an omnitool, charge it up, and try to break some stone bricks of any kind.

#### Affected Versions (Do *not* use "*latest*"):

- CLib: 1.0.2.31
- MatterOverdrive: 0.6.0.176
- Forge: 14.23.4.2705
- Minecraft: 1.12.2

**Comment by Buuz135** [comment]
Are you sure that those bricks doesnt have a silverfish?

**Comment by Buuz135** [comment]
(Waila and TOP will show them as if they were normal bricks)

**Comment by Shahelion** [comment]
They do not. I crafted and placed all of the non-vanilla ones, and even a few of the vanilla ones, and have been breaking them fairly steadily as I convert this tower to Livingwood/Livingrock. No Silverfish at all.

It also applies to other blocks that can't be Silverfish eggs, as shown in the linked album.

**Comment by adrwa** [comment]
Can this be reproduced outside of the twilight forest?

**Comment by Zsashas** [comment]
Yes.

**Comment by Shahelion** [comment]
Yes. 
![2018-06-23_22 53 17](https://user-images.githubusercontent.com/6917535/41816369-4baf16f0-7738-11e8-8b7c-d8eea3865e83.png)
