### ISSUE TITLE
Crash between Fairy Lights and MO

### ISSUE THREAD

**Issue by Secretname2009** [MatterOverdrive/MatterOverdrive-Legacy-Edition#153]
I teleported home using Journeymap and it randomly crashed with this error.
VanillaFix was installed so it supressed the crash but it reported that Fairy Lights and MO was the cause.
Just gonna figure out which mod is the cause and get help for it.
[crash-2018-06-30_13.45.14-client.txt](https://github.com/MatterOverdrive/MatterOverdrive/files/2151675/crash-2018-06-30_13.45.14-client.txt)

**Comment by adrwa** [comment]
Please use the bug report template, its there for a reason

**Comment by Secretname2009** [comment]
Ah sorry, i recreated the issue using the template.
