### ISSUE TITLE
Crash between Fairy Lights and MO

### ISSUE THREAD

**Issue by Secretname2009** [MatterOverdrive/MatterOverdrive-Legacy-Edition#154]
#### Issue Description:
I recently turned into an Android and went out from my home to look for something, i returned home and it all of a sudden crashes.
The area i returned to does not have fairy lights placed around as i know of, i might have some in chests. 

#### What happens:
It would crash back to the launcher but for me VanillaFix mod supresses it and returns to menu.

#### What you expected to happen:
Load the world and continue playing

#### How to reproduce:
Attempt to join the world that has both mods installed

#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive: 0.6.0.176
- Forge: 14.23.4.2707
- Minecraft: 1.12.2
- Fairy Lights: 2.1.2
#### Crash report, if relevent
[crash-2018-06-30_15.30.24-client.txt](https://github.com/MatterOverdrive/MatterOverdrive/files/2151744/crash-2018-06-30_15.30.24-client.txt)

**Comment by Secretname2009** [comment]
After removing Fairy Lights mod, it still crashes, but with Solar Flux Reborn.

**Comment by Lynncubus** [comment]
Also experiencing this issue

[crash-2018-08-10_15.06.18-client.txt](https://github.com/MatterOverdrive/MatterOverdrive/files/2277973/crash-2018-08-10_15.06.18-client.txt)
