### ISSUE TITLE
MO and Drones interaction crash

### ISSUE THREAD

**Issue by DevTimur** [MatterOverdrive/MatterOverdrive-Legacy-Edition#156]
#### Issue Description:
When you got Matter Overdrive ,and [Drones](https://minecraft.curseforge.com/projects/drones) something cause crash

#### Affected Versions (Do *not* use "*latest*"):
- MatterOverdrive:MatterOverdrive-1.12.2-0.6.0.176-universal
- Forge:
- Minecraft:

#### Crash report, if relevent
https://pastebin.com/C03gxt4R

**Comment by adrwa** [comment]
Wont fix, duplicate of #83
