### ISSUE TITLE
No recipes for most tritanium crates

### ISSUE THREAD

**Issue by cloakable** [MatterOverdrive/MatterOverdrive-Legacy-Edition#157]
#### Issue Description:
There are only recipes for the red tritanium crate and the uncoloured one; all other crates are uncraftable.

#### What happens:
No recipe output

#### What you expected to happen:
Get a crate of that colour

#### How to reproduce:
Try to craft a coloured tritanium crate other than red

#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive: 0.6.0.176 beta 6
- Forge: 2705
- Minecraft: 1.12.2

#### Crash report, if relevent
[pastebin/gist link here]

**Comment by adrwa** [comment]
Intended
