### ISSUE TITLE
Zoom-In/Scope Bug As Android

### ISSUE THREAD

**Issue by UchihaAvenger** [MatterOverdrive/MatterOverdrive-Legacy-Edition#159]
When trying to use optifine's zoom in or the scope for phaser rifle and ion sniper, it doesn't zoom in on target when pressing zoom key for optifine or right-clicking on weapons with scopes.

Scopes or zoom features don't zoom?

To zoom in on my target for a more accurate shot

Become an android. Hold a weapon with a scope and hold right-click/press zoom key from optifine

- MatterOverdrive: 1.12.2-0.6.0.176 BETA 6
- Forge: 14.23.4.2739
- Minecraft: 1.12.2

EDIT:

I'm sorry this was apparently some odd config setting that I accidentally disabled

**Comment by The-Unnamed-Engineer** [comment]
I have experienced this issue as well.

- MatterOverdrive: 0.6.0.182
- Forge: 14.23.4.2705
- Minecraft: 1.12.2
