### ISSUE TITLE
Crash when looking at android tables hologram, also, android parts don't overlay on skin like they used to

### ISSUE THREAD

**Issue by Darkmega18** [MatterOverdrive/MatterOverdrive-Legacy-Edition#160]
#### Issue Description:
After switching to being an android to check stuff out while testing, I ended up looking at the hologram in the android table. but it crashes me and spits out an error, now I can't get back into world cause I instantly recrash as soon as I go back in.

#### What you expected to happen:
to be able to look at and admire the graphics without blowing up.

#### How to reproduce:
look at the displayed hologram, probably with the same mods that I have if possible (I can provide an exported twitch profile of my current set up if you need?), and after equipping all basic ranged android parts plus a spine.

#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive: MatterOverdrive-1.12.2-0.6.0.176-universal.jar
- Forge: forge-1.12.2-14.23.4.2705.jar
- Minecraft: 1.12.2

#### Crash report, if relevent
https://pastebin.com/QNd42R15

**Comment by The-Unnamed-Engineer** [comment]
The parts render was removed by the original dev before Coded took over the project so those will not be available any time in the future of MO, however they may reappear in MOH.

**Comment by Darkmega18** [comment]
MOH? also, any idea why this crashes then? :V I kinda gathered they got removed, since I saw nothing about configging them or otherwise, but figured I'd ask.

**Comment by The-Unnamed-Engineer** [comment]
MOH, MatterOverdrive Horizon edition, basically a complete rebuild of MO from the ground up, to allow the current devs to add better features without dealing with the mess left behind by the original creator.
As for the crash, I would guess it's a model issue caused by another one of your mods.

**Comment by Darkmega18** [comment]
neato. hopefully fixed then I guess. :D
