### ISSUE TITLE
Spam There was a problem while ticking

### ISSUE THREAD

**Issue by xxlio109** [MatterOverdrive/MatterOverdrive-Legacy-Edition#166]
#### Issue Description:
I don't know what happened at the time.
#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive: 1.12.2-0.6.0.176-universal
- Forge:2705
- Minecraft:1.12.2

#### Crash report, if relevent
https://gist.github.com/xxlio109/fac1295639b75dea9ca71c7180b0f403

**Comment by adrwa** [comment]
Try reproduce without sponge
