### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by Diamondman121314** [MatterOverdrive/MatterOverdrive-Legacy-Edition#169]
#### Issue Description:
When using the `/mo_gen` command, it gives an errors.

#### What happens:
Command gives error when being used.

#### What you expected to happen:
Command should work as intended.

#### How to reproduce:
Just doing /mo_gen creates an error in console and doesn't work after that.

#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive: 0.6.0.192
- Forge: 14.23.4.2747
- Minecraft: 1.12.2

#### Crash report, if relevent
https://pastebin.com/SL9vWfQe

**Comment by adrwa** [comment]
Dont use mo gen then? its an internal debug tool, not something players should use

**Comment by Diamondman121314** [comment]
Well, what else is supposed to be done when no structures are seen? Not one structure has been found throughout exploring for hours. I realize it's still in beta, but I would hope to still be able to see these structures.

Anomalies spawn, but seem very weird in how they spawn, ores also spawn, but the structures are the only things that don't.

**Comment by adrwa** [comment]
Because structures aren't a thing in the 1.12 version, thats why they dont generate

**Comment by Diamondman121314** [comment]
Any idea when those could be seen or just to wait? I'm fine with waiting, just want to know if they'll be happening.
