### ISSUE TITLE
All items contained in Tritanium Crate completely lost when picking up with Tritanium Wrench.

### ISSUE THREAD

**Issue by DSquirrelGM** [MatterOverdrive/MatterOverdrive-Legacy-Edition#173]
All items contained in Tritanium Crate completely lost when picking up with Tritanium Wrench!

1.12.2-0.6.0.197

**Comment by Lykrast** [comment]
Similarly, picking up a Matter Replicator with the wrench voids the Tritanium Plates put inside as shielding.

**Comment by zzyasia** [comment]
the same with upgrade contained in machine
