### ISSUE TITLE
Server crash on launch

### ISSUE THREAD

**Issue by IronworksProductions** [MatterOverdrive/MatterOverdrive-Legacy-Edition#174]
#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive:MatterOverdrive-1.12.2-0.6.0.197 PRE 1
- Forge:2705
- Minecraft:1.12.2

#### Crash report, if relevent
[pastebin/gist link here]
https://gist.github.com/nacjm/8fbbfa21eb55fad26258feb10c64c9f0

**Comment by IronworksProductions** [comment]
Did someone even see this? Or has it been 9 days and I don't even know if I can add the mod back into the modpack.

**Comment by adrwa** [comment]
Has been seen but please, do not feel entitled to instant support or any support, this will be fixed when i or another team member has the time to do so, not when you demand.

**Comment by IronworksProductions** [comment]
I was not expecting it to be fixed I know how long these can take. I am a dev myself. I just wanted to know that it was seen that way it did not seem like it was ignored. I have been waiting for about 4 months for random things to figure out a bug I saw so I just wanted to make sure I did not find another one of those.
