### ISSUE TITLE
Crash with latest versions of optifine

### ISSUE THREAD

**Issue by philipjholm** [MatterOverdrive/MatterOverdrive-Legacy-Edition#176]
#### What happens:
I have just tried starting this mod with only below versions of optifine (one at a time of course) and it makes the game crash when creating a new world. 

OptiFine 1.12.2 HD U E2
OptiFine 1.12.2 HD U E1

I must use following version to make it work:  
OptiFine 1.12.2 HD U D3

#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive: MatterOverdrive-1.12.2-0.6.0.197 PRE 1 & MatterOverdrive-1.12.2-0.6.0.176 BETA 6
- Forge: 1.12.2-forge1.12.2-14.23.4.2758
- Minecraft: 1.12.2

#### Crash report, if relevent
https://pastebin.com/mM4Tc6S0

**Comment by adrwa** [comment]
No
