### ISSUE TITLE
[1.12] Disabling generation does not work

### ISSUE THREAD

**Issue by wormzjl** [MatterOverdrive/MatterOverdrive-Legacy-Edition#177]
I have config as follows:
```
"world gen" {
    # Should Matter Overdrive Buildings Generate aka ImageGen [default: true]
    B:"generate buildings"=false

    # A blacklist of all the Dimensions ores shouldn't spawn in
    I:ore_gen_blacklist <
        -1
        0
        1
        2
     >

    # Should Matter Overdrive Ore Blocks be Generated ?
    B:"spawn ores"=false

    # Should other Matter Overdrive World Blocks be Generated?
    B:"spawn other"=false
    B:spawn.tile.dilithium_ore=false
    B:spawn.tile.gravitational_anomaly=false
    B:spawn.tile.tritanium_ore=false

    gravitational_anomaly {
        # Gravitational Anomaly Dimension ID blacklist
        I:blacklist <
         >

        # Spawn Chance of Gravity Anomaly pre chunk [range: 0.0 ~ 1.0, default: 0.05]
        S:"gravitational anomaly spawn chance"=0.0

        # Gravitational Anomaly Dimension ID whitelist
        I:whitelist <
            -1
            0
         >
    }

}
```

But ores and gravitational anomalies are still generating in the world

**Comment by philipjholm** [comment]
I have exactly the same problem. Seems that the config is not working at all in the latest version (MatterOverdrive-1.12.2-0.6.0.197 PRE 1).

**Comment by adrwa** [comment]
"I have the same issue" does not help solve the issue and just spams up the issues, please dont do it

**Comment by wormzjl** [comment]
Rougue android spawns also doesn't follow the config

**Comment by Draskh** [comment]
I was about to change the settings for MatterOvderdrive and I could not find any file, where the configuration could be stored. I changed anythin in the GUI, but there where no generated files. I have just a file named "MatterOverdrive" classifed as "file" in the directory of this mod. This file is also empty.
