### ISSUE TITLE
Matter Analyzer generates power instead of consuming it

### ISSUE THREAD

**Issue by Lykrast** [MatterOverdrive/MatterOverdrive-Legacy-Edition#179]
#### Issue Description:

The Matter Analyzer generates power instead of consuming it.

#### What happens:

When running the Matter Analyzer no power is being drained, instead it fills its own buffer as it works.

#### What you expected to happen:

Power being drained and consumed when the Matter Analyzer runs.

#### How to reproduce:

Place Matter Analyzer down with stuff to analyze, put just enough power to work the first tick then watch the buffer fill.

#### Affected Versions:

- Matter Overdrive: 0.6.0.197
- Forge: 14.23.4.2739
- Minecraft: 1.12.2

**Comment by adrwa** [comment]
...thats.. fun? weird one
