### ISSUE TITLE
registering of tritanium and dilithium

### ISSUE THREAD

**Issue by 0Navis0** [MatterOverdrive/MatterOverdrive-Legacy-Edition#184]
I noticed Tritanium and Dilithium aren't registered in ore dictionnary, it prevents compatibility with other mods that uses T(r)itanium and Dilithium, notably TechReborn and TAIGA.

**Comment by Draskh** [comment]
Tritanium is not the same as Titanium of TR, that is why this two materials are not unified. And they are in the OreDictionary as well and fully compatible with TAIGA. You should check your modlist if some removes registration.
