### ISSUE TITLE
Give the current pipes some love

### ISSUE THREAD

**Issue by adrwa** [MatterOverdrive/MatterOverdrive-Legacy-Edition#20]
Matter network & transport pipes are a bit temperamental, needs fixing up with a possible rewrite

**Comment by Muirrum** [comment]
@TheCodedOne Isn't this fixed in latest push?

**Comment by adrwa** [comment]
Not completely

**Comment by Muirrum** [comment]
Ok, just making sure.

**Comment by ChilledDayz** [comment]
Any news on a fix for the pipes?
