### ISSUE TITLE
Structure Generation

### ISSUE THREAD

**Issue by vastangel** [MatterOverdrive/MatterOverdrive-Legacy-Edition#25]
Structures are not generating even in the latest 0.6.0 beta.
Tried a superflat world with just MO and CLib loaded,
Also have tried to force generate with mo_gen command and the structure still only half generates.

I'm looking forward to this working out as this is one of my 2 favourite mods.

**Comment by Muirrum** [comment]
World gen has been broken since the 1.10.2 beta, we're working on it.

**Comment by DBotThePony** [comment]
Does this mean you are unable to get pill to become an android in survival legally?

**Comment by adrwa** [comment]
yes, it is a beta people are warned that not everything works as intended yet

**Comment by Muirrum** [comment]
Wait I could have sworn that world gen worked in my latest build.
