### ISSUE TITLE
As android hunger is not refilled by power

### ISSUE THREAD

**Issue by DBotThePony** [MatterOverdrive/MatterOverdrive-Legacy-Edition#28]
And player can even die as android from starvation

**Comment by Muirrum** [comment]
Androids shouldn't even have hunger in the first place.

**Comment by DBotThePony** [comment]
I know, so im reporting. Hunger bar *can* deplete as android

**Comment by DBotThePony** [comment]
![2018-02-13_18 39 55](https://user-images.githubusercontent.com/6339511/36148088-50b23b48-10ed-11e8-9468-35bdf6f9de80.png)

**Comment by YuRaNnNzZZ** [comment]
^ tested in a clean environment (only clib and MO installed)

**Comment by adrwa** [comment]
After looking at the code this is working as intended, there is an android upgrade called Zero Calories which uses power to refil food
