### ISSUE TITLE
Bring back the old phaser model

### ISSUE THREAD

**Issue by lag42** [MatterOverdrive/MatterOverdrive-Legacy-Edition#32]

**Comment by adrwa** [comment]
theres a small problem of we dont have the original files anymore, unless i can find somewhere that has them this cant happen :(

**Comment by Muirrum** [comment]
They're not on Simeon's repo?

**Comment by adrwa** [comment]
not as far as i can see

**Comment by Muirrum** [comment]
Did you check the 1.7.10 branch? That's the last place I saw them, and they're present in the last 1.7.10 version.

**Comment by lag42** [comment]
I might be able to find a way to steal it out of an old version if nothing else

**Comment by Muirrum** [comment]
I'm going to check the repo.

**Comment by Muirrum** [comment]
Found them.
Phaser1.obj: https://github.com/simeonradivoev/MatterOverdrive/blob/1.7.10/src/main/resources/assets/mo/models/item/phaser.obj

Phaser 2.obj: https://github.com/simeonradivoev/MatterOverdrive/blob/1.7.10/src/main/resources/assets/mo/models/item/phaser2.obj

**Comment by Muirrum** [comment]
This should've been closed a little while ago, as coded and I discussed this in Discord.
