### ISSUE TITLE
[1.12] Server crash

### ISSUE THREAD

**Issue by Vitali8** [MatterOverdrive/MatterOverdrive-Legacy-Edition#33]
Hey there! During server startup something went wrong. "Fatal errors were detected during the transition from CONSTRUCTING to PREINITIALIZATION. Loading cannot continue". Before this, in the console flashed these lines: 
`[21:40:10] [Server thread/INFO] [clib]: Construction (Started)`
`[21:40:10] [Server thread/ERROR] [clib]: > Error loading proxies, matteroverdrive.proxy.CommonProxy`
`[21:40:10] [Server thread/ERROR] [clib]: > Error injecting proxy, PROXY`
`[21:40:10] [Server thread/INFO] [clib]: Construction (Ended after 7ms)`.
[Here server's crash log.](https://gist.github.com/Vitali8/6739f0f5d077cd6ee7130239745729b0)
About server:
    SpongeAPI: 7.1.0-SNAPSHOT-6aa4e43
    SpongeForge: 1.12.2-2611-7.1.0-BETA-2914
    Minecraft Forge: 14.23.2.2615

**Comment by adrwa** [comment]
oops, theres a thing i missed

**Comment by adrwa** [comment]
reopening just until i release the next beta so that people dont duplicate
