### ISSUE TITLE
[1.12.2 - 0.6.0.40 BETA 1] Server crash on startup with only Matter Overdrive and CLib.

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [MatterOverdrive/MatterOverdrive-Legacy-Edition#34]
**Forge version:  14.23.2.2615**
**Minecraft version: 1.12.2**
**CLib version: 1.0.2.31**
**Matter Overdrive version: 0.6.0.40 BETA 1**
**Crashlogs & Logs:**
[`Crash Log`](https://pastebin.com/MLB98gRF)
[`Earlystartup Log`](https://pastebin.com/E1UuHFuQ)
[`FML-Server-Latest Log`](https://pastebin.com/Y948p1Py)

Wanted to play with friends with mods and Matter Overdrive, server has been crashed after a seconds, when started. Seems, Matter Overdrive tried to load CommonProxy, but something goes wrong and it crashing a server.

**Comment by adrwa** [comment]
duplicate of #33

**Comment by DenisMasterHerobrine** [comment]
Oops. Sorry, for duplicating.

**Comment by adrwa** [comment]
its not a problem, i can understand duplicates when the other issue is closed
