### ISSUE TITLE
crash game when I tried to install an energy cell from a mod mekanism

### ISSUE THREAD

**Issue by KiraLinux** [MatterOverdrive/MatterOverdrive-Legacy-Edition#43]
I tried to install an energy cell in one of the weapons in the weapons table

crash logs in the archive
[crash-2018-02-15_00.48.00-client.zip](https://github.com/MatterOverdrive/MatterOverdrive/files/1725778/crash-2018-02-15_00.48.00-client.zip)

**Comment by adrwa** [comment]
duplicate of #26
