### ISSUE TITLE
Omni Tool cant mining 

### ISSUE THREAD

**Issue by KiraLinux** [MatterOverdrive/MatterOverdrive-Legacy-Edition#44]
can't mining blocks from chisel mod and quark mod

**Comment by lag42** [comment]
it can't break blocks from quite a few mods actually, not just chisel and quark

**Comment by KiraLinux** [comment]
it can't even break vanilla stone bricks

**Comment by Shahelion** [comment]
Will this fix be released soon?

**Comment by Buuz135** [comment]
This is out in the `MatterOverdrive 1.12.2 0.6.0.108 BETA 3` version in curseforge

**Comment by Shahelion** [comment]
I have 1.12.2-0.6.0.157 and it's still a bug, though.

I saw the 0.6.0 release milestone and thought at first it meant the non-beta release of 0.6.0.

**Comment by Shahelion** [comment]
Version 176: 

![2018-06-21_21 43 00](https://user-images.githubusercontent.com/6917535/41758241-3a1c3672-759c-11e8-8eb3-7b1a174aa197.png)

It takes so much longer than it should to break it, and drops nothing when it does.

I'm trying to figure out what determines what it can or can't mine, and can't find a pattern yet. It seems to work for Stone Slabs, as well as any kind of wood including modded, but not mossy, cracked, or normal stone bricks. Maybe it's just full pickaxe blocks that don't work?

EDIT: Hmm, nope not that. It can mine smooth stone and ores.
