### ISSUE TITLE
game font changing

### ISSUE THREAD

**Issue by Zygus42** [MatterOverdrive/MatterOverdrive-Legacy-Edition#47]
MatterOverdrive-1.12.2-0.6.0.40-universal
MatterOverdrive-CLib-1.0.2.30-universal

Using the Data Pad changes the game font to something modern looking, so that's all the tool tips, the game buttons, the chat etc, until the next time you restart Minecraft.

**Comment by adrwa** [comment]
Unable to reproduce with just MO

**Comment by Zygus42** [comment]
Only mods:
MatterOverdrive-1.12.2-0.6.0.108-universal
CLib-1.0.2.31-universal
forge-1.12.2-14.23.2.2611-installer-win

Before:
![2018-03-29_11 07 59](https://user-images.githubusercontent.com/20757445/38068070-ad4147b6-3341-11e8-847d-75f5862bcd5a.png)
![2018-03-29_11 07 51](https://user-images.githubusercontent.com/20757445/38068068-abf3792e-3341-11e8-851a-d25cf954495f.png)


After:
![2018-03-29_11 06 44](https://user-images.githubusercontent.com/20757445/38068078-b4611616-3341-11e8-9045-c986f6d8ae09.png)
![2018-03-29_11 06 52](https://user-images.githubusercontent.com/20757445/38068080-b5887a8e-3341-11e8-9018-b9fc1cd6fc51.png)
