### ISSUE TITLE
Fusion reactor does not generate electricity

### ISSUE THREAD

**Issue by DarkEvoli** [MatterOverdrive/MatterOverdrive-Legacy-Edition#52]
The fusion reactor does not generate electricity in the latest version.

![2018-02-15_21 01 55](https://user-images.githubusercontent.com/16646883/36278128-1fecc24c-1293-11e8-8cfb-7ca9a5aa9ec2.png)

![2018-02-15_21 02 00](https://user-images.githubusercontent.com/16646883/36278201-5adc7d0c-1293-11e8-896b-dd291f48025f.png)

**Comment by DaroMoon** [comment]
my fusion reactor is broken too, only mines producing too much energy, 100 million rf per tick, it only seems to happen when i try to transfer energy from it using a phantom face or a draconic energy crystal, not using a phantom face to the factor, but just using it as a wire

![2018-02-18_13 29 19](https://user-images.githubusercontent.com/36605731/36355352-db0f3ab4-14af-11e8-9b78-5b6842d86117.png)

**Comment by adrwa** [comment]
I believe this is fixed
