### ISSUE TITLE
hundreds of Anomalies

### ISSUE THREAD

**Issue by ShaCraft** [MatterOverdrive/MatterOverdrive-Legacy-Edition#66]
Created a new world on my modded test pack. found some areas that have 100s of Anomalies.

**Comment by DBotThePony** [comment]
because they are now being debugged

**Comment by Vitali8** [comment]
And because in the config file specified by default:
`# Spawn Chance of Gravity Anomaly pre chunk [range: 0.0 ~ 1.0, default: 5.0]`
        `S:"gravitational anomaly spawn chance"=5.0`
