### ISSUE TITLE
Fusion Reactor Generating 100 Million Rf/t

### ISSUE THREAD

**Issue by DaroMoon** [MatterOverdrive/MatterOverdrive-Legacy-Edition#72]
my reactor is set up normally but when i attach a phantom face to it, not linking the reactor to the phantom face, the reactor suddenly starts producing 100 million rf/t
![2018-02-18_13 29 19](https://user-images.githubusercontent.com/36605731/36355390-7b8c4ad6-14b0-11e8-8f08-b4a802d327fb.png)
CLib-1.0.2.30-universal
MatterOverdrive-1.12.2-0.6.0.40-universal
Forge 14.23.1.2566
also happens in
CLib-1.0.2.31-universal
MatterOverdrive-1.12.2-0.6.0.75-universal
Forge 14.23.1.2566

**Comment by adrwa** [comment]
Please provide more information like mod version, forge version, clib version

**Comment by DaroMoon** [comment]
forge and stuff listed now

**Comment by adrwa** [comment]
Can you try reproduce in latest MO

**Comment by DaroMoon** [comment]
The same bug does infact still occur in the latest MatterOverdrive-1.12.2-0.6.0.148-universal

**Comment by Rsslone** [comment]
Same here. I'm on version 1.12.2-0.6.0.157.

This is the setup. https://i.imgur.com/DmqU41f.png
I am running spongeforge if that could make a difference.

**Comment by ruifung** [comment]
MO 1.12.2-0.6.0.176

Reactor -> TE Cryo-stabilized fluxducts -> Flux Plug (Flux Networks), it's outputting a crazy 200MFE/t despite the GUI stating 6902 FE/t
