### ISSUE TITLE
[1.12.2] 0.6.0.75 BETA 2 Shift clicking isolinear circuits into and out of the molecular inscriber deletes the item

### ISSUE THREAD

**Issue by Blackcatmaxy** [MatterOverdrive/MatterOverdrive-Legacy-Edition#73]
Note this on a server running the same mods and forge

Minecraft 1.12.2 and Matter Overdrive version 0.6.0.75 BETA 2 Clib 1.0.2.31 and Forge 14.23.2.2612 
My personal modpack Interstellar Engineering https://minecraft.curseforge.com/projects/interstellar-engineering for modlist

Basically if you shift click a circuit into the molecular inscriber it just vanishes and you have to make a new circuit and if you try to take out a finished circuit by shift clicking.

Also the molecular inscriber is missing the top part that kinda 3D printed in the 1.7.10 version

**Comment by adrwa** [comment]
Is anything shown in the logs when shift clicking an item

**Comment by Blackcatmaxy** [comment]
Nothing on server or client logs, although I wasn't able to reproduce shift clicking something into, when I shift clicked something out it deleted itself and the counterpart already in my inventory that it was presumably going to stack with.

**Comment by adrwa** [comment]
closing as this is technically fixed, replaced by #94
