### ISSUE TITLE
Incredible Amount of TileEntities

### ISSUE THREAD

**Issue by Xaikii** [MatterOverdrive/MatterOverdrive-Legacy-Edition#74]
I was creating a new world(and that happens at every new world) and noticed hard tps drops such as high ms... I've tracked down the root of the problem(see pic). I dont know what causes this, but well... before I reached a "sweet" amount of 20k TileEntities of gravitational_anomaly and the world was unplayable... 

If it is somehow necessary I tracked it down via [ChunkPregenerator](https://minecraft.curseforge.com/projects/chunkpregenerator?gameCategorySlug=mc-mods&projectID=267193).

![2018-02-19_02 34 09](https://user-images.githubusercontent.com/25128633/36359724-27c6ca84-151e-11e8-9d33-7f1961edb2f3.png)

**Comment by adrwa** [comment]
duplicates #66
