### ISSUE TITLE
Dismantling a Borg Charging Station causes dupe

### ISSUE THREAD

**Issue by K4N0** [MatterOverdrive/MatterOverdrive-Legacy-Edition#80]
Dismantling a Charging Station Causes it to duplicate itself. Shift-right click with a tritanium wrench = dupe every time. Takes forever to break with a pick axe too.
![bitmoji](https://render.bitstrips.com/v2/cpanel/2af24209-ea90-4912-9223-4c54c650559a-1b2f4e6c-2e26-42df-a5ae-892d691a479f-v1.png?transparent=1&palette=1&width=246)

**Comment by DBotThePony** [comment]
already fixed, but not released

**Comment by adrwa** [comment]
Please for the love of god check for duplicates before posting, #62

**Comment by K4N0** [comment]
Is it really such a big deal that you have to post that type of negative attitude? I did look for it. i must have just missed it. But please for the love of god don't post such whinny little girl comments like that. Are you a man?

**Comment by adrwa** [comment]
Yes it is a big deal, every duplicate wastes my time because I have to test the same bug all over again, github has a search in issues feature for this exact reason.

**Comment by K4N0** [comment]
How about you update more often? I'm very sorry that you feel like this is a big waste of time. Maybe you are not in the right place. If i new it was a duplicate, i would have just closed it and be done with it. I think you need a system in place to mark down fixes for the current version. A quick list of things fixed before an update would probably help you lots so that you can check a condensed list instead of checking the code. You won't see me post any more bug or dupes if i find em, cause i really don't want to have to deal with your kind anymore.
