### ISSUE TITLE
[1.12.2] Crash on startup "Duplicate stat id"

### ISSUE THREAD

**Issue by aking4125** [MatterOverdrive/MatterOverdrive-Legacy-Edition#83]
[crash-2018-02-25_18.15.04-client.txt](https://github.com/MatterOverdrive/MatterOverdrive/files/1756830/crash-2018-02-25_18.15.04-client.txt)

Crashes at around the 5/7 progress when loading on the client on my modpack. May have something to do with a different mod. Not sure. Removing the mod stops this particular crash and the pack loads normally.

**Comment by DBotThePony** [comment]
Thats a lotta mods. Try to reproduce on minimal set of mods.

**Comment by Mattabase** [comment]
It looks like it is a crash with the Drones mod.

https://minecraft.curseforge.com/projects/drones

**Comment by adrwa** [comment]
oh well thats brilliant, a closed sauce mod with no issue tracker either

**Comment by aking4125** [comment]
Drones huh. I'll double check. I don't remember if I had it in that pack.

**Comment by adrwa** [comment]
you did have drones, its in the crash report

**Comment by aking4125** [comment]
I deleted that pack and completely redid it. So I'm building that same one again.

**Comment by aking4125** [comment]
It took some time due to irl stuff. But when drones is installed. Crash. When it's not, it works. I guess it's that mod. I should try the latest version of both mods to see if it fixes it. Not like it matters, this one looks more interesting.

**Comment by adrwa** [comment]
I've tried to contact the drones developer but unable to do so, there is nothing i can do
