### ISSUE TITLE
Pattern Monitors do not find completed patterns

### ISSUE THREAD

**Issue by SyntaxError73** [MatterOverdrive/MatterOverdrive-Legacy-Edition#84]
Hello. I am running Matter Overdrive on Minecraft 1.12.2. I wanted to create a matter network system, but the pattern monitor does not find completed patterns, and is always showing the 0 on the screen.

No matter how i have my network set up, the 0 is still on screen.
Here is a network with few cables.
![2018-02-26_16 58 28](https://user-images.githubusercontent.com/36898706/36749163-f0dad122-1bc7-11e8-89d1-b31100f2fe92.png)

Here is my updated network with many cables.

![2018-02-27_14 02 53](https://user-images.githubusercontent.com/36898706/36749278-4ccdadd8-1bc8-11e8-9ae6-56a35b2cec6f.png)

I have 3 patterns stored in my storage blocks currently. The Grass block, Apple, and the Inactive Gem Base Item from a mod called KAGIC.

It could be an issue with the Pattern Storage, Monitor or Pattern Drive. (The lights in the Pattern drive item don't light up when a pattern is completed.) that is all.

**Comment by adrwa** [comment]
Fixed
