### ISSUE TITLE
This mod does not support rebinding Attack/Use actions to keyboard

### ISSUE THREAD

**Issue by handicraftsman** [MatterOverdrive/MatterOverdrive-Legacy-Edition#88]

**Comment by handicraftsman** [comment]
Nope, it supports. But plasma rifle seems buggy.

**Comment by handicraftsman** [comment]
* shotgun

**Comment by handicraftsman** [comment]
Okay, all missile-shooting weapons don't work when using keyboard instead of mouse

**Comment by handicraftsman** [comment]
Attack key (left click by default) does not work, while Use key (right click by default) works

**Comment by adrwa** [comment]
This isnt something I can fix, if its not working its a bug with minecraft as a whole
