### ISSUE TITLE
Some Recipes arent implemented

### ISSUE THREAD

**Issue by adrwa** [MatterOverdrive/MatterOverdrive-Legacy-Edition#9]
Due to 1.12 the way MO previously did recipes wont work, we either need to switch to json or move all the recipe registration to the events

**Comment by Muirrum** [comment]
Well what are the benefits of either solution?

**Comment by adrwa** [comment]
JSON is the method that should be used unless a recipe requires very special mechanics

**Comment by Muirrum** [comment]
Ok, so what needs to happen to implement JSON recipes?

**Comment by adrwa** [comment]
writing the jsons, i'll add a recipe converter to convert the current MO recipes into json

**Comment by Muirrum** [comment]
Ok

**Comment by Muirrum** [comment]
@TheCodedOne this done?

**Comment by adrwa** [comment]
not entirely, theres a few items that are recipeless still

**Comment by adrwa** [comment]
closed by 94e5093
