### ISSUE TITLE
Gravitational Stabilizer Vertical Comparability 

### ISSUE THREAD

**Issue by Vyraal1** [MatterOverdrive/MatterOverdrive-Legacy-Edition#91]
Going off of this [picture](https://mo.simeonradivoev.com/wp-content/uploads/2015/05/Stabalized-Gravitational-Anomaly.png), it seems like the Stabilizer should have vertical capability to point upwards / downwards. In game I've tested the wrench, which seems to have the ability to rotate stairs and other blocks, but does not have the ability to rotate any MO blocks (specifically Fusion Controller, Stabilizer). 

Would it be possible to at least implement positioning based on sneak+clicking the block? eg. to have it face downwards you can either right click place the stabilizer onto the bottom side of a block above it, OR sneak+right click place the stabilizer onto the TOP side of a block below it.

Or maybe get the wrench to do it.

**Comment by adrwa** [comment]
in 1.12 the stabilizer is not able to be placed on the vertical plane

**Comment by Darkosto** [comment]
May I suggest to replace that image then? It caused me and will most likely cause many users confusion when the mods instruction manual shows you can place it vertically.

Sorry to comment on a closed issue, but I just spent a few minutes trying to figure out why I couldn't place them vertically even though the image shows you can.
