### ISSUE TITLE
[Suggestion] Shift+Click Functionality into Machine GUI's inventory slots / UI Feedback

### ISSUE THREAD

**Issue by Vyraal1** [MatterOverdrive/MatterOverdrive-Legacy-Edition#94]
Without JEI support, it's somewhat difficult to determine which items go where at first. Given the Matter Decomposer UI: 
![image](https://user-images.githubusercontent.com/26587049/37067359-5c7ee9f4-2177-11e8-8832-0b02050c3620.png)

I initially didn't notice the slots so far to the left for inputs. Normally for modded minecraft if the direct input slot isn't immediately apparent, I rely on shift+clicking items to figure out where they go, so it was tempo-breaking to try slots randomly. My suggestion is to either _implement shift+click Item Stacks into the appropriate area_ (eg. compatible batteries into the battery slot, compatible items into the matter slot), or _possibly putting a brighter border to the slots_ on the left to indicate their presence.

**Comment by adrwa** [comment]
shift+clicking was temporarily disabled as the items sometimes went into the void, it'll be re implemented once i have time to go and look at the container code

**Comment by adrwa** [comment]
related to #73
