### ISSUE TITLE
Matter Network Cables have no tool and do not break easily / other

### ISSUE THREAD

**Issue by Vyraal1** [MatterOverdrive/MatterOverdrive-Legacy-Edition#98]
![image](https://user-images.githubusercontent.com/26587049/37068795-8400dc56-217e-11e8-9bf8-e7503dcce6a1.png)

Was trying to use Matter Network Cables to try and connect my Pattern Storage with my Matter Analyser, however I misplaced one and tried to break it, seemed to break at same speed at breaking stone with my bare hands. Would it be possible to allow the wrench to immediately disassemble it or allow for breaking with picks/tools?

Also the Matter Network cables don't seem to connect at all to the Pattern Storage (going off of 1.7.10 tutorial video)

**Comment by adrwa** [comment]
yeah pipes are fucked, #20
